# Generated by Django 2.2.15 on 2020-10-19 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0127_auto_20200907_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentCompetency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.Competency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_competencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
