# Generated by Django 2.0.5 on 2018-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL([
            "UPDATE notifications_notification SET verb = 'COMMENTED' WHERE verb = 'commented on';",
            "UPDATE notifications_notification SET verb = 'NEEDS_APPROVAL' WHERE verb = '- Green assessment approval needed -';",
            "UPDATE notifications_notification SET verb = 'APPROVED' WHERE verb = 'approved assessment';",
            "UPDATE notifications_notification SET verb = 'NEEDS_WORK' WHERE verb = 'marked assessment as needs more work - ';",
        ],
        [
            "UPDATE notifications_notification SET verb = 'commented on' WHERE verb = 'COMMENTED';",
            "UPDATE notifications_notification SET verb = '- Green assessment approval needed -' WHERE verb = 'NEEDS_APPROVAL';",
            "UPDATE notifications_notification SET verb = 'approved assessment' WHERE verb = 'APPROVED';",
            "UPDATE notifications_notification SET verb = 'marked assessment as needs more work - ' WHERE verb = 'NEEDS_WORK';",
        ]),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('COMMENTED', 'commented'), ('NEEDS_APPROVAL', 'needs approval'), ('APPROVED', 'approved'), ('NEEDS_WORK', 'NEEDS_WORK')], max_length=255),
        ),
    ]
