# Generated by Django 2.0.5 on 2019-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20181221_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('COMMENTED', 'commented on'), ('NEEDS_APPROVAL', 'needs approval on'), ('APPROVED', 'approved assessment for'), ('NEEDS_WORK', 'marked assessment as needs work for')], max_length=255),
        ),
    ]
