# Generated by Django 2.0.5 on 2019-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190104_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('COMMENTED', 'commented on'), ('NEEDS_APPROVAL', 'needs approval on'), ('APPROVED', 'approved assessment for'), ('NEEDS_WORK', 'marked assessment as needs work for'), ('NEW_USER', 'New user'), ('NEW_ACTION_ITEM', 'created an action item for'), ('AI_NEEDS_APPROVAL', 'needs approval for an action item on'), ('AI_APPROVED', 'approved action item for')], max_length=255),
        ),
    ]
