# Generated by Django 2.0.5 on 2020-04-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_auto_20200418_2238'),
        ('notifications', '0007_noticetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
    ]
