# Generated by Django 2.0.5 on 2018-06-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180606_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemglobal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
