# Generated by Django 2.0.5 on 2018-07-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180618_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='video',
        ),
    ]
