# Generated by Django 2.0.5 on 2018-08-24 22:35

from django.db import migrations, models
from django.contrib.auth.models import Group


def change_student_group_to_user(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    group = Group.objects.using(db_alias).filter(name="Student").first()
    if group:
        group.name = "User"
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_competency_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cohort',
            field=models.ManyToManyField(blank=True, help_text='Users should only be in ONE group. Mentor can be in multiple groups.', related_name='users', to='dashboard.Cohort'),
        ),
        migrations.RunPython(change_student_group_to_user),
    ]
