# Generated by Django 2.0.5 on 2018-10-01 22:06

from django.db import migrations, models


def copy_roadmap(apps, schema_editor):
    User = apps.get_model('dashboard', 'User')
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        if user.roadmap:
            user.roadmaps.add(user.roadmap)


def copy_roadmap_reverse(apps, schema_editor):
    User = apps.get_model('dashboard', 'User')
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        if user.roadmaps.first():
            user.roadmap = user.roadmaps.first()
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180824_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roadmaps',
            field=models.ManyToManyField(blank=True, related_name='users', to='dashboard.Roadmap'),
        ),
        migrations.RunPython(copy_roadmap, copy_roadmap_reverse),
        migrations.RemoveField(
            model_name='user',
            name='roadmap',
        ),
    ]
