# Generated by Django 2.0.5 on 2018-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181001_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=models.CharField(blank=True, help_text="This is the 'Question?' that's used in the Stage overview", max_length=1024),
        ),
    ]
