# Generated by Django 2.0.5 on 2018-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181023_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=models.CharField(blank=True, help_text="This is the 'Question?' that's used in the Stage overview", max_length=2048),
        ),
        migrations.AlterField(
            model_name='competency',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
