# Generated by Django 2.0.5 on 2018-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20181023_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('0', 'Grey'), ('1', 'Red'), ('2', 'Yellow'), ('3', 'Green')], default='1', max_length=1),
        ),
    ]
