# Generated by Django 2.0.5 on 2018-11-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20181114_1100'),
        ('notifications', '0001_initial'),
        ('postman','0001_initial'),
    ]

    operations = [
        migrations.RunSQL([
            'ALTER DATABASE myroadmap CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_actionitemassessment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_actionitemglobal CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_actionitemglobal_cohort CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_assessment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_cohort CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_comment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_company CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_competency CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_note CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_roadmap CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_stage CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_user_coach CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_user_cohort CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_user_groups CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_user_mentors CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_user_roadmaps CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE dashboard_user_user_permissions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE notifications_notification CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
            'ALTER TABLE postman_message CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
        ])
    ]