# Generated by Django 2.0.5 on 2019-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190102_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
    ]
