# Generated by Django 2.0.5 on 2019-02-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_company_requires_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
