# Generated by Django 2.0.5 on 2019-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20190211_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_email',
            field=models.BooleanField(default=True),
        ),
    ]
