# Generated by Django 2.0.5 on 2019-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20190301_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemassessment',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
