# Generated by Django 2.0.5 on 2019-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_actionitemassessment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemglobal',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
