# Generated by Django 2.0.5 on 2019-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_actionitemglobal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='only_coach_asssigns_roadmaps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
