# Generated by Django 2.0.5 on 2019-08-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20190731_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users_can_attach_files',
            field=models.BooleanField(default=True),
        ),
    ]
