# Generated by Django 2.0.5 on 2019-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_company_users_can_attach_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemassessment',
            name='notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
