# Generated by Django 2.0.5 on 2019-09-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20190905_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actionitemassessment',
            unique_together={('student', 'parent')},
        ),
    ]
