# Generated by Django 2.0.5 on 2019-09-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20190905_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='conversations',
            field=models.BooleanField(default=False),
        ),
    ]
