# Generated by Django 2.0.5 on 2019-09-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_company_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
