# Generated by Django 2.0.5 on 2019-09-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20190913_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users_can_assign_coach',
            field=models.BooleanField(default=True),
        ),
    ]
