# Generated by Django 2.0.5 on 2019-09-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_company_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users_can_erase_their_account',
            field=models.BooleanField(default=False),
        ),
    ]
