# Generated by Django 2.0.5 on 2019-09-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_company_users_can_erase_their_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='icon',
            field=models.FileField(blank=True, upload_to='images/roadmap_icons/'),
        ),
    ]
