# Generated by Django 2.0.5 on 2019-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20191003_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='coach_can_asssign_roadmaps',
            field=models.BooleanField(default=True),
        ),
    ]
