# Generated by Django 2.0.5 on 2019-10-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20191004_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_synonym',
            field=models.CharField(blank=True, default='User', max_length=50),
        ),
    ]
