# Generated by Django 2.0.5 on 2019-10-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_company_user_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dark_ui',
            field=models.BooleanField(default=True),
        ),
    ]
