# Generated by Django 2.0.5 on 2019-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_company_competency_notes_journal_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='coach_notes',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='stage',
            name='coach_notes',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='competency',
            name='green_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='competency',
            name='red_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='competency',
            name='yellow_description',
            field=models.CharField(max_length=500),
        ),
    ]
