# Generated by Django 2.0.5 on 2019-10-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20191009_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coach_notes',
            field=models.BooleanField(default=False),
        ),
    ]
