# Generated by Django 2.0.5 on 2019-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_company_coach_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='nhfscsrkknzjpiehhjqjzmsozwunirquuzdvznfuengmixknjq'),
        ),
    ]
