# Generated by Django 2.0.5 on 2019-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20191009_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='wsJdXoMTWGDT698WEdAOtk0NVtAQLdPkm0rH6bKv1oksFSoMD7lnj9dflYX3vKRIcSn5WodHsjq'),
        ),
    ]
