# Generated by Django 2.0.5 on 2019-10-10 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20191009_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='is_archived',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='AV241VjJqdgU37c9kgeJSSxEjXOyKtkEl4VAuY8LNV06qtDK3Mp4yAJ5m7J6yVKHMjhSHlJb8JJ'),
        ),
    ]
