# Generated by Django 2.0.5 on 2019-10-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20191009_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_roadmaps',
            field=models.ManyToManyField(blank=True, to='dashboard.Roadmap'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='rsj8wkYalLzBQxantcjhOegEcuzgL3uTRJ2a3R3g5JSpLqZEYYjWdExRp84VXeay3I0pbYiRWTl'),
        ),
    ]
