# Generated by Django 2.0.5 on 2019-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20191010_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='rxzpyBoIuZ42RiVxsZEigqSxYER7UIFuFDN16Ji3XqMWu9djPxtRzc0D25K2ld8wK3zoBaOWIME'),
        ),
        migrations.AlterField(
            model_name='user',
            name='archived_roadmaps',
            field=models.ManyToManyField(blank=True, related_name='archived_roadmaps', to='dashboard.Roadmap'),
        ),
    ]
