# Generated by Django 2.0.5 on 2019-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20191010_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='company',
            name='archive_roadmaps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='ylYIt3TRNMepjwQljHOLG9UvWswEWME7POXccYV08V15OulmtMqQFWGVUEYKONzI1eE5J0LFJny'),
        ),
    ]
