# Generated by Django 2.0.5 on 2019-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20191010_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemglobal',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[(1, 'User'), (2, 'Coach')], max_length=200),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='LBosw6qhcrtyRkdJl2QRcWUNTryXdK1X902V8VdZLWKWaKPAl1thpKYnCk2e6SbRqhEq2xEWjWG'),
        ),
    ]
