# Generated by Django 2.0.5 on 2019-10-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20191014_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitemglobal',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='32pXK6bzzbRvNBl1dbJIL6OXlUKHdaDu0U8SxS8FKLV1BQZPJkVA9RHbItjyVVVgOD1bZx0TAQY'),
        ),
    ]
