# Generated by Django 2.0.5 on 2019-10-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20191014_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='roadmaps',
            field=models.ManyToManyField(blank=True, related_name='roadmaps', to='dashboard.Roadmap'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='9dOnirLBJJYX2CzoJMyU8vpf4SleXGAxri78DbslXp2uYYct5fcYbS19KzdtXwsFR8j5FjMi0jr'),
        ),
    ]
