# Generated by Django 2.0.5 on 2019-10-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20191014_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group_specific_roadmaps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='7kab0ufFOCwSsLqgOMJN4GyMM8tnGefJmNd8FMRf5oZLV1jhZH82Jna2pRRz0NRSLZc4rtI9dL0'),
        ),
    ]
