# Generated by Django 2.0.5 on 2019-10-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_auto_20191016_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='roadmaps',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Cohort'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='w93fF4BZAkU2EKPTD6mLfqp7vpQda2ZANeW4DpmLVP95ZZ3IcECPi7xvamE9A6XIUOHnJLOGgi5'),
        ),
    ]
