# Generated by Django 2.0.5 on 2019-10-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20191017_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='cohorts',
        ),
        migrations.AddField(
            model_name='cohort',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Roadmap'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='roadmaps',
            field=models.ManyToManyField(blank=True, related_name='roadmaps', to='dashboard.Roadmap'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='W2ix6i0RFcYPVhmubO4V3qDnwHr7xArZzNepQDNqFXh5btdwC118W3lf47XAZDuz1oiCPJGjlsP'),
        ),
    ]
