# Generated by Django 2.0.5 on 2019-10-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20191017_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_cohorts', to='dashboard.Cohort'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='cohorts',
            field=models.ManyToManyField(blank=True, related_name='cohorts', to='dashboard.Cohort'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='L64qR34hgAyZ4B657qkCEkcZOlhbreIjhmSywlDZfJWEa0xnDM9MBcEhmcU2Naj6kNvL1XHbnRJ'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort_roadmaps', to='dashboard.Roadmap'),
        ),
    ]
