# Generated by Django 2.0.5 on 2019-10-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20191017_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='cohort',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='wOZhox9QGuOaNHLk226NiwpcTXQSGPg4Ur9dq9pXoSuMHKvPIhDBfiskNgRPx5x9DrmVOq0vEfC'),
        ),
    ]
