# Generated by Django 2.0.5 on 2019-10-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_auto_20191022_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='hidden_for',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='md3PGQM7XNwbeTG45Z6r0i8365U9AknCWAHCz9S6lq5d0kxBi9VQET75bpdv9MA0b5SqBpKQl1B'),
        ),
    ]
