# Generated by Django 2.0.5 on 2019-10-22 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20191022_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='Z0CD54HxAY9m3iTveZkg8jSP4DjLULm3ZcwfP6OMVuqljWr8ALMO0Obz1NiyNaP7ie9rZkwEFPA'),
        ),
    ]
