# Generated by Django 2.0.5 on 2019-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20191022_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coach_admin_assign_user_specifc_objectives',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='coach_admin_edit_visibility_user_objectives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='KQcWNX8NyPvRiTjrpKnwTdm68J2QZP0GB1taMMtQjOjA6JKbnY54SsXmJNAx0syZWGZcFXOkPbh'),
        ),
    ]
