# Generated by Django 2.0.5 on 2019-10-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_auto_20191022_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='assign_to_all_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='hidden_from_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='03k0QKBCn5ZQAdIUWKHPnPfprvmb0PvABO7XQTjeDFwHnsSL7kDqvsfd47ajl00u1wugCbuSGl3'),
        ),
    ]
