# Generated by Django 2.0.5 on 2019-10-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20191022_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ('pinned',)},
        ),
        migrations.AddField(
            model_name='company',
            name='hide_roadmaps_from_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='pin_roadmaps_for_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='PAjCrcqjWFj2Ib60bMkOGf1kPApTFNdtRTrZva2fjRUzBlvAdmlePlKptXNHDmP63C92Gxif9E0'),
        ),
    ]
