# Generated by Django 2.0.5 on 2019-10-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20191023_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='oNIAZ0pKsq8ZfGvql4nXxEax7JEum4hXvms1nEiZdd6YybtALbuqiPCmtycmt279bzhxxM94rqG'),
        ),
    ]
