# Generated by Django 2.0.5 on 2019-10-23 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20191023_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='VnJ5mtnDCjedWSkKTpcuGzutwEpFl3Pc8lCSwmAVA7opRSdbpB1SN47a0tcW8OhZQbckRvWlr5x'),
        ),
        migrations.AlterField(
            model_name='roadmapassignments',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Roadmap'),
        ),
        migrations.AlterField(
            model_name='roadmapassignments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
