# Generated by Django 2.0.5 on 2019-10-24 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20191023_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='75uIpPv61LJrlA4KX2wuJcxtpitClzFuxJtQWaCEj71D5dirQscsREZFkZb6jllC37Hw2yp7yNe'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roadmapassignments',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
