# Generated by Django 2.0.5 on 2019-10-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_auto_20191024_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemassessment',
            name='send_follow_up_email_on_due_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='2kklWthcprBlp0x0BkHASaEqyZbo3h4vRQaQU7wnIMa4T9soNvF86r7qtdNPKmCovxvFh2bzOpn'),
        ),
    ]
