# Generated by Django 2.0.5 on 2019-10-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_auto_20191025_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users_cant_add_action_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='mxRCS1qtORt1dViNb33uNZLD3ZUdugFEZBaQlfnDsAfL24DoiRkcUgBLf8s9BsFYrREROQIPyZL'),
        ),
    ]
