# Generated by Django 2.0.5 on 2019-10-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20191028_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users_cant_add_action_items',
        ),
        migrations.AddField(
            model_name='company',
            name='users_can_add_action_items',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='UUJZ8agxIk5s3zTv87pDKPQToSszKnfdSc89MMwMfU4fObK5nO85vvNxdUAXetrvnNtLjhb7GDf'),
        ),
    ]
