# Generated by Django 2.0.5 on 2019-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_auto_20191028_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='hidden_from_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='eDijsYy7jotQq4CkqsvytnkUmtzw7fnnIBk6jl8RvG0k6JB43nbik5K307ukKhU2x2hj19ftGXl'),
        ),
    ]
