# Generated by Django 2.0.5 on 2019-11-11 06:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_auto_20191110_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('order', models.IntegerField(default=0)),
                ('competency', models.ForeignKey(limit_choices_to={'student': None}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Competency')),
            ],
        ),
        migrations.CreateModel(
            name='ContentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Competency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ContentGlobal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='DAlRoi3zQ5irdwyXBCMvuIC7tAsHtIzsH7dWZvldadikrKad4peSSd5bByeP5b5qdHZ31WExjlK'),
        ),
        migrations.AlterUniqueTogether(
            name='contentresponse',
            unique_together={('student', 'parent')},
        ),
    ]
