# Generated by Django 2.0.5 on 2019-11-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_auto_20191110_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='l98YdlceNdng80lk8FIwFoLxyd1D2Y1I7kIPMcFgiEBAmyQlzVukg3F2SfFt50jK4FLCQGMcXtz'),
        ),
        migrations.AlterField(
            model_name='contentresponse',
            name='response',
            field=models.TextField(blank=True, max_length=2024, null=True),
        ),
    ]
