# Generated by Django 2.0.5 on 2019-11-11 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_auto_20191110_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='lo6oyMI6d0kOJaAWpKuvC3t1qJdTL4WFpYmXA5px3Vqgl4F9ng6dNt9l7KtBuJUhbhoAKlZCVhC'),
        ),
        migrations.AlterField(
            model_name='contentresponse',
            name='response',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
