# Generated by Django 2.0.5 on 2019-11-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_auto_20191111_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='ai_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competency',
            name='comments_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='gukTbDcM9euZcaOyegGIzLA9IelOnSyJjrENrGoLtS1Qi8j2HUOoVqVSBP1PxhLMnzF9SQ8THiI'),
        ),
    ]
