# Generated by Django 2.0.5 on 2019-11-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_auto_20191112_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='users_can_edit_ai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='users_can_edit_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='WCEfDjWMaEXf4SwHcWqTEGYzCxWm3A8i9LuVH662rALOko8DybzikvL9vtJFisDmdKwIoPct9x1'),
        ),
    ]
