# Generated by Django 2.0.5 on 2019-11-21 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_auto_20191113_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('marked_done', models.BooleanField(default=False)),
                ('date_marked_done', models.DateField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='u34CtIDdNkfq2NDFPnmvI1RGAuDo0h7UNE72Qbe0YrCwJHOSRRmgPqE3PbDH5UaPvdG3qHMVqzp'),
        ),
    ]
