# Generated by Django 2.0.5 on 2019-11-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_auto_20191121_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupitem',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='sg5r9hrVq8D6Q2o9bWWEPCucj6SWweic1uOc7NaqDNvWj6sGI1HJkjJlb6tLafRDGTCEzDDG7m8'),
        ),
    ]
