# Generated by Django 2.0.5 on 2019-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_auto_20191121_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='date_attached',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='rj1hr9XO4Dp2Y5iQhX0WFfjRgHKDX9YcM3LX6mx8G8S1FHKxEzLYhCFnBWnX5PmA5riv83qMzsI'),
        ),
    ]
