# Generated by Django 2.0.5 on 2019-11-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_auto_20191126_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='KBUzNEAcKKRZYyOvogD71fFTNBIWUXiB5SvKrjdwqJFx4AuR6Ve7BcKHBwhIemCqraxIMlyUr7Z'),
        ),
    ]
