# Generated by Django 2.0.5 on 2019-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_auto_20191126_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coaches_admin_can_assess_objectives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='XC6dEtsa4H9sXk63vWtx40iweonwyM15f4F98ioMfQAk7KRrPSShskXIYIGT4x0c6OWpUWujtHF'),
        ),
    ]
