# Generated by Django 2.0.5 on 2019-12-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_auto_20191219_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_welcome_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='XZLiVwkWzv26bi8qQ4VC3ftMI4fhSLzRiWRyFs8ExzMHAR5ZUmmu6VsB7rNThehsx123G4cU5YD'),
        ),
    ]
