# Generated by Django 2.0.5 on 2019-12-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_auto_20191219_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='follow_up_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='9tXtFy98NLUWeNNMmNLYkDwKbsRGC8OLrQEzKbTR2azKuCQjP8VrRahWVbCNAREwvgBz9rs2zYe'),
        ),
    ]
