# Generated by Django 2.0.5 on 2020-01-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_auto_20191220_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_green_assessment',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_red_assessment',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_yellow_assessment',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='UxPeJQIBVA2iXV9voJ6OSYH8HMR243FK41mdzxHrr8pUEh3Rv5gsk6Fv1sy5LrfuijjY5f1shss'),
        ),
    ]
