# Generated by Django 2.0.5 on 2020-01-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_auto_20200107_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='UYrXc8TICASVOZXU7OhRjEbChbqSxvUZ8SRuuTw3zQmAftocbXdfykEdPBaE2XIra5JfS3ngmJ6'),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_green_assessment',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_red_assessment',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_yellow_assessment',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
