# Generated by Django 2.0.5 on 2020-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_auto_20200107_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='X6nJ2siYz66SUmr4TOEaNnU01il8jItOgsm40sMzK26pCgzxjSPzy67uNLEwp14BhJ2TrT9h7MN'),
        ),
    ]
