# Generated by Django 2.0.5 on 2020-03-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_auto_20200226_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='attachments_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='Cy7Ex3BGrlAeoWkIeKc4lfn3ZbRV6wezvpigE21o5oIXLJ1ASOCcklxRvk4eTphlRVIZ44T2SmL'),
        ),
    ]
