# Generated by Django 2.0.5 on 2020-03-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_auto_20200310_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='hidden_for_all_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='14x4JPw1QDKSSHwIRZfnWLQyVRq5ie3mZy1Xs1kblMp1GIEXOIaZJ2sF2dmfOYvJIOLM5AhMidQ'),
        ),
    ]
