# Generated by Django 2.0.5 on 2020-03-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_auto_20200323_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users_can_assign_specific_coaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='jdEh04r7fAgziCqRWx7bZ3qCpWHVwvVIUmzp3z3Ky6LP1gMolWz7qK91Dm0y0qB3YD7hAldcZNR'),
        ),
    ]
