# Generated by Django 2.0.5 on 2020-04-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_auto_20200330_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='company_users', to='dashboard.Company'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='Rq3IeDYGyMJlqmGlxyFZmWQzKYxWCUZoRfmAIzZAe9VtWEKWJ5xgNID5W5n68JzYR81eub2RwwW'),
        ),
    ]
