# Generated by Django 2.0.5 on 2020-04-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0107_auto_20200414_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcompany',
            name='cohort',
            field=models.ManyToManyField(blank=True, to='dashboard.Cohort'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='JSrZQ3HhnnjEffXraxJnIhwBXu2AEMmDJrJS1V53IzodAPysEvyQGxUuzpqeHP1aUEbIkQClXvM'),
        ),
    ]
