# Generated by Django 2.0.5 on 2020-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_auto_20200418_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='privacy_policy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='H8zuKPeRni9NuvAJhdfu0V0TjQ78LJZE4TTJD2yJYboWzsbxV9asgnEj4H0nCKfEOVVhqKr7zpj'),
        ),
    ]
