# Generated by Django 2.0.5 on 2020-04-27 23:51

from django.db import migrations, models


def assign_companies(apps, schema_editor):
    # Add current company field data to assigned companies field
    User = apps.get_model('dashboard', 'User')
    AssignedCompany = apps.get_model('dashboard', 'AssignedCompany')
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        if user.company:
            if not user.assigned_companies.filter(company=user.company):
                assigned_company = AssignedCompany.objects.using(db_alias).create(company=user.company, is_approved=user.is_approved)
                assigned_company.groups.set(user.groups.all())
                assigned_company.cohort.set(user.cohort.all())
                user.assigned_companies.add(assigned_company)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20200423_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='7HUHvQiPBgjXRahlRB4W8s586zPeSezqCiwKOSEU45ncN847ucnB7oP9cwxf9FIX6JOqBWhiAAT'),
        ),
        migrations.RunPython(assign_companies),
    ]
