# Generated by Django 2.0.5 on 2020-05-06 04:22

from django.db import migrations, models


def remove_duplicate_assigned_companies(apps, schema_editor):
    # Add current company field data to assigned companies field
    User = apps.get_model('dashboard', 'User')
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        for company in user.companies.all():
            for assigned_company in user.assigned_companies.filter(company=company).reverse():
                if user.assigned_companies.filter(company=company).count() > 1:
                    assigned_company.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_auto_20200427_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='gj3Sb6V2pG2yXrmpo7DyqMziONzQIVENS7hWZhh6NQ42LLOOupozWooEjNI3LdNMXE68wrjxj8i'),
        ),
        migrations.RunPython(remove_duplicate_assigned_companies),
    ]
