# Generated by Django 2.0.5 on 2020-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0112_auto_20200505_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assessment_synonym',
            field=models.CharField(blank=True, default='Assessment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='TplwyvTEYsx3NahEFe9nzoretroMKSWtokjNhQPCD8givYrFNeo0rYXpXotsPyMd89BMrDph4el'),
        ),
    ]
