# Generated by Django 2.0.5 on 2020-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_auto_20200602_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coaches_approved_green_assessments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='3zt3ffb3QRKZEazLFZCMV6qmvXUNNCMnU3FF99P7ApCWavMjR5LdHjkAfiDnVJmkm5pOxtVoKNn'),
        ),
    ]
