# Generated by Django 2.0.5 on 2020-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_auto_20200604_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='coaches_approved_green_assessments',
            new_name='coaches_approve_green_assessments',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='HCmGtr1XxUMXuvirDyZl3qKu8PnToYSzxL2k4ljddJBHtHNk4548qaSDXUj65nWK8jAL2YEEn5M'),
        ),
    ]
