# Generated by Django 2.0.5 on 2020-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0115_auto_20200604_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_green_assessment_prompt',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='company',
            name='default_red_assessment_prompt',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='company',
            name='default_yellow_assessment_prompt',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='xfV7JYZx8HgmmzNzAEcZEyVul5isFtBwLkQJwsCirnnsLyOIBg1cNUMFXbWTiGi4kYWZK73Dpx4'),
        ),
    ]
