# Generated by Django 2.0.5 on 2020-07-22 20:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_auto_20200604_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='69gYcIec8j5rmfrOKn03dfyYXIFjYnSi9ImLSrM457NUdGrl2PvqbTkTYquynK1PZ37KFe5oR6w'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
