# Generated by Django 2.0.5 on 2020-07-29 22:07

import ckeditor.fields
from django.db import migrations, models


def copy_descriptions(apps, schema_editor):
    # Add old company field data to new companies field
    ActionItemGlobal = apps.get_model('dashboard', 'ActionItemGlobal')
    db_alias = schema_editor.connection.alias
    for item in ActionItemGlobal.objects.using(db_alias).all():
        if item.description:
            item.title = item.description
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0117_auto_20200722_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemglobal',
            name='aiAttachment',
            field=models.FileField(blank=True, upload_to='ai_files/'),
        ),
        migrations.AddField(
            model_name='actionitemglobal',
            name='aiDescription',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='actionitemglobal',
            name='category',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='actionitemglobal',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitemglobal',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitemglobal',
            name='resolutions',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='actionitemglobal',
            name='title',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.RunPython(copy_descriptions),
    ]
