# Generated by Django 2.0.5 on 2020-07-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_auto_20200729_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitemglobal',
            name='description',
        ),
    ]
