# Generated by Django 2.0.5 on 2020-07-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_remove_actionitemglobal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitemglobal',
            name='resolutions',
        ),
    ]
