# Generated by Django 2.0.5 on 2020-07-31 05:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0120_remove_actionitemglobal_resolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemglobal',
            name='resolutions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mark_complete', 'mark complete'), ('requires_approval', 'requires approval'), ('attach_file', 'attach file'), ('attach_screen_recording', 'attach screen recording'), ('input_text', 'input text'), ('attach_audio_recording', 'attach audio recording')], max_length=101, null=True),
        ),
    ]
