# Generated by Django 2.0.5 on 2020-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_actionitemglobal_resolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemassessment',
            name='assessmentAttachment',
            field=models.FileField(blank=True, upload_to='assessment_files/'),
        ),
        migrations.AddField(
            model_name='actionitemassessment',
            name='assessmentAudio',
            field=models.FileField(blank=True, upload_to='assessment_files/'),
        ),
        migrations.AddField(
            model_name='actionitemassessment',
            name='assessmentScreen',
            field=models.FileField(blank=True, upload_to='assessment_files/'),
        ),
    ]
