# Generated by Django 2.0.5 on 2020-08-03 22:51

from django.db import migrations, models


def setup_ai_resolutions(apps, schema_editor):
    # Add old company field data to new companies field
    ActionItemGlobal = apps.get_model('dashboard', 'ActionItemGlobal')
    db_alias = schema_editor.connection.alias
    for item in ActionItemGlobal.objects.using(db_alias).all():
        item.resolutions = 'mark_complete,requires_approval,input_text'
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_attachment_actionitem'),
    ]

    operations = [
       migrations.RunPython(setup_ai_resolutions),
    ]
