# Generated by Django 2.0.5 on 2020-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0124_actionitemglobal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemassessment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
