# Generated by Django 2.0.5 on 2020-08-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0125_auto_20200803_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitemglobal',
            old_name='title',
            new_name='aiTitle',
        ),
    ]
