# Generated by Django 2.2.15 on 2020-09-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_auto_20200803_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemassessment',
            name='send_follow_up_email_on_due_date',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='assignedcompany',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='assign_roadmaps_to_all_users',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='coach_admin_assign_user_specifc_objectives',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='coach_admin_edit_visibility_user_objectives',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='coach_can_asssign_roadmaps',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='coach_notes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='coaches_admin_can_assess_objectives',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='coaches_approve_green_assessments',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='competency_notes_journal_section',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='dark_ui',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='follow_up_schedule',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='group_specific_roadmaps',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='hide_roadmaps_from_users',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='pin_roadmaps_for_users',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='private_labeled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='requires_approval',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='show_print_competency_detail_button',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_can_asssign_roadmaps',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='users_can_add_action_items',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='users_can_assign_coach',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='users_can_attach_files',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='ai_visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='attachments_visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='comments_visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='user_defined',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='assign_to_all_users',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='hidden_from_users',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='pinned',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='simplified_ai',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='users_can_edit_ai',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='users_can_edit_content',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='hidden_from_users',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
