# Generated by Django 2.2.15 on 2020-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_auto_20201020_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_category',
            field=models.CharField(blank=True, choices=[('SCREEN', 'Screen'), ('AUDIO', 'Audio'), ('ATTACHMENT', 'Attachment')], max_length=16),
        ),
    ]
