# Generated by Django 2.2.15 on 2020-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0131_auto_20201215_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='users_can_assign_coach',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
