# Generated by Django 2.2.15 on 2020-12-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0132_auto_20201218_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users_can_invite_coach',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
