# Generated by Django 2.2.15 on 2020-12-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0135_auto_20201218_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='slider_status',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
