# Generated by Django 2.2.15 on 2021-01-13 18:42

from django.db import migrations


def migrate_forward(apps, schema_editor):
    company_model = apps.get_model("dashboard", "Company")
    db_alias = schema_editor.connection.alias
    company_model.objects.using(db_alias).filter(dark_ui=True, default_theme='').update(default_theme='dark')


def reverse_migration(apps, schema_editor):
    company_model = apps.get_model("dashboard", "Company")
    db_alias = schema_editor.connection.alias
    company_model.objects.using(db_alias).filter(default_theme='dark').update(dark_ui=True, default_theme='')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0137_auto_20210113_1026'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, reverse_migration),
        migrations.RemoveField(
            model_name='company',
            name='dark_ui',
        ),
    ]
