# Generated by Django 2.2.15 on 2021-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0138_auto_20210113_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='django_frontend_base_url',
            field=models.URLField(blank=True, help_text='Format: https://app.myroadmap.io'),
        ),
        migrations.AddField(
            model_name='company',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Format: support@myroadmap.io, will be prepended with the company name, i.e. MyRoadmap &lt;support@myroadmap.io&gt;', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='company',
            name='react_frontend_base_url',
            field=models.URLField(blank=True, help_text='Format: https://react-app.myroadmap.io'),
        ),
    ]
