# Generated by Django 2.2.15 on 2021-01-15 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0139_auto_20210115_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
