# Generated by Django 2.2.15 on 2021-02-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0140_auto_20210115_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
