from django.conf.urls import url, include, re_path
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from .views import AssessmentAuthorizedViewSet

from push_notifications.api.rest_framework import GCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'device/gcm', GCMDeviceAuthorizedViewSet)
router.register(r'assessment', AssessmentAuthorizedViewSet)

from . import views
from dashboard.exports import basic_csv_export, company_export

urlpatterns = [
    path('', views.home_redirect, name='index'),
    # path('roadmap-list/', views.roadmap_list, name='roadmap_list'),
    path('active-company/', login_required(views.choose_active_company), name='choose_active_company'),
    path('my-roadmaps/', login_required(views.roadmaps), name='roadmaps'),
    path('my-action-items/', login_required(views.my_action_items), name='my_action_items'),
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
    path('super_dashboard/', login_required(views.super_dashboard), name='super_dashboard'),
    path('basic_csv_export/', login_required(basic_csv_export), name='basic_csv_export'),
    path('company_export/', login_required(company_export), name='company_export'),
    path('profile/', login_required(views.ProfileView.as_view()), name='profile'),
    path('change-password/', login_required(views.ChangePasswordView.as_view()), name='change_password'),
    path('logout/', views.log_out, name='logout'),
    path('users/', login_required(views.SCMList.as_view()), kwargs=dict(who='users'), name='users'),
    path('users/<int:user_id>/unsubscribe/<str:token>/', views.email_unsubscribe, {'unsubscribe': True}, name='email_unsubscribe'),
    path('users/<int:user_id>/subscribe/<str:token>/', views.email_unsubscribe, {'unsubscribe': False}, name='email_subscribe'),
    path('coaches/', login_required(views.SCMList.as_view()), kwargs=dict(who='coaches'), name='coaches'),
    path('coaches/invite/', login_required(views.coaches_invite), name='coaches_invite'),
    path('coaches/invite/accept/', views.coaches_invite_accept, name='coaches_invite_accept'),
    path('mentors/', login_required(views.SCMList.as_view()), kwargs=dict(who='mentors'), name='mentors'),
    path('profile-detail/<int:pk>/', login_required(views.ProfileDetailView.as_view()), name='profile_detail'),
    path('competency/<int:pk>/', login_required(views.CompetencyDetailView.as_view()), name='competency'),
    path('competency/<int:competency_id>/user/<int:student_id>/screen-record', login_required(views.CompetencyScreenRecord.as_view()), name='competency_screen_record'),
    path('competency/<int:competency_id>/user/<int:student_id>/audio-record', login_required(views.competency_audio_record), name='competency_audio_record'),
    path('competency/add/', login_required(views.CompetencyAddView.as_view()), name='competency_add'),
    path('competency/<int:pk>/edit/', login_required(views.CompetencyDetailView.as_view()), kwargs={'edit': True}, name='competency_edit'),
    path('action-items/', login_required(views.action_items), name='action_items'),
    path('action-items/<int:item_id>/screen-record', login_required(views.CompetencyScreenRecord.as_view()), name='ai_screen_record'),
    path('action-items/<int:item_id>/audio-record', login_required(views.competency_audio_record), name='ai_audio_record'),
    path('follow-up-items/', login_required(views.follow_up_items), name='follow_up_items'),
    path('questions/', login_required(views.questions), name='questions'),
    path('content/', login_required(views.content), name='content'),
    path('my-roadmaps/<int:roadmap_id>/', login_required(views.roadmap), name='roadmap'),
    path('roadmaps/<int:roadmap_id>/add/', login_required(views.roadmap_add), name='roadmap_add'),
    path('roadmaps/<int:roadmap_id>/remove/', login_required(views.roadmap_remove), name='roadmap_remove'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path('edit-coach/<int:pk>/', login_required(views.coach_view_2), name='edit_coach'),
    path('my-roadmaps/<int:roadmap_id>/user-edit-assigned-coaches/', views.user_edit_assigned_coaches, name='user_edit_assigned_coaches'),
    path('assign-coach/<int:roadmap_id>/<int:coach_id>/<int:student_id>', views.assign_coach, name='assign_coach'),
    path('remove-coach/<int:roadmap_id>/<int:coach_id>/<int:student_id>', views.remove_coach, name='remove_coach'),
    path('not-approved/', login_required(views.not_approved), name='not_approved'),
    path('action-item/<int:pk>/', login_required(views.ActionItemDetail.as_view()), name='action_item'),
    path('follow-up-item/<int:pk>/', login_required(views.FollowUpItemDetail.as_view()), name='follow_up_item'),
    path('gloabl-action-item/<int:pk>/', login_required(views.GlobalActionItemDetail.as_view()), name='global_action_item'),
    path('question/<int:pk>/', login_required(views.QuestionDetail.as_view()), name='question'),
    path('gloabl-question/<int:pk>/', login_required(views.GlobalQuestionDetail.as_view()), name='global_question'),
    path('content/<int:pk>/', login_required(views.ContentDetail.as_view()), name='content'),
    path('global-content/<int:pk>/', login_required(views.GlobalContentDetail.as_view()), name='global_content'),
    path('embed/', views.embed, name='embed'),
    path('notify/', views.sendmail),
    path('bouncereport/', views.email_bounce_report),

    url(r'^', include(router.urls)),

    #ajax routes
    path('ajax-', include([
        path('action-items/', login_required(views.ajax_action_items), name='ajax_action_items'),
        path('action-item-add/', login_required(views.ajax_action_item_add), name='ajax_action_item_add'),
        path('global-action-item-edit/', login_required(views.ajax_global_action_item_edit), name='ajax_global_action_item_edit'),
        path('follow-up-items/', login_required(views.ajax_follow_up_items), name='ajax_follow_up_items'),
        path('follow-up-item-add/', login_required(views.ajax_follow_up_item_add), name='ajax_follow_up_item_add'),
        path('questions/', login_required(views.ajax_questions), name='ajax_questions'),
        path('question-add/', login_required(views.ajax_question_add), name='ajax_question_add'),
        path('content/', login_required(views.ajax_content), name='ajax_content'),
        path('content-add/', login_required(views.ajax_content_add), name='ajax_content_add'),
        path('attachment-delete/', login_required(views.ajax_attachment_delete), name='ajax_attachment_delete'),
        path('add-stage/', login_required(views.ajax_add_stage), name='ajax_add_stage'),
        path('approve-user/<int:pk>', login_required(views.ajax_approve_user), name='ajax_approve_user'),
        path('hide-action-item/<int:pk>', login_required(views.ajax_hide_ai), name='ajax_hide_ai'),
        path('show-action-item/<int:pk>', login_required(views.ajax_show_ai), name='ajax_show_ai'),
        path('hide-comments/<int:pk>', login_required(views.ajax_hide_comments), name='ajax_hide_comments'),
        path('show-comments/<int:pk>', login_required(views.ajax_show_comments), name='ajax_show_comments'),
        path('hide-attachments/<int:pk>', login_required(views.ajax_hide_attachments), name='ajax_hide_attachments'),
        path('show-attachments/<int:pk>', login_required(views.ajax_show_attachments), name='ajax_show_attachments'),
        path('hide-competency/<int:pk>', login_required(views.ajax_hide_competency), name='ajax_hide_competency'),
        path('show-competency/<int:pk>', login_required(views.ajax_show_competency), name='ajax_show_competency'),
        path('publish-roadmap/<int:pk>', login_required(views.ajax_publish_roadmap), name='ajax_publish_roadmap'),
        path('competencies/', login_required(views.ajax_get_competencies), name='ajax_competencies'),
        path('delete-competency/', login_required(views.ajax_delete_competency), name='ajax_delete_competency'),
        path('delete-stage/', login_required(views.ajax_delete_stage), name='ajax_delete_stage'),
        path('edit-competency-note/', login_required(views.ajax_edit_competency_note), name='ajax_edit_competency_note'),
        path('roadmap-icon/', login_required(views.ajax_roadmap_icon), name='ajax_roadmap_icon'),
        path('edit-roadmap-title/', login_required(views.ajax_edit_roadmap_title), name='ajax_edit_roadmap_title'),
        path('edit-roadmap-description/', login_required(views.ajax_edit_roadmap_description), name='ajax_edit_roadmap_description'),
        path('edit-stage/', login_required(views.ajax_edit_stage), name='ajax_edit_stage'),
        path('profile-pic/', login_required(views.ajax_profile_pic), name='ajax_profile_pic'),
        path('profile-pic-delete/', login_required(views.ajax_profile_pic_delete), name='ajax_profile_pic_delete'),
        path('sidebar/', login_required(views.ajax_sidebar), name='ajax_sidebar'),
        path('sort-action-items/', login_required(views.ajax_sort_action_items), name='ajax_sort_action_items'),
        path('sort-questions/', login_required(views.ajax_sort_questions), name='ajax_sort_questions'),
        path('sort-competencies/', login_required(views.ajax_sort_competencies), name='ajax_sort_competencies'),
        path('sort-stages/', login_required(views.ajax_sort_stages), name='ajax_sort_stages'),
        path('edit-ai-note/', login_required(views.ajax_edit_ai_note), name='ajax_edit_ai_note'),
        path('edit-q-answer/', login_required(views.ajax_edit_q_answer), name='ajax_edit_q_answer'),
        path('edit-c-response/', login_required(views.ajax_edit_c_response), name='ajax_edit_c_response'),
        path('register-device/', login_required(views.ajax_register_device), name='ajax_register_device'),
        path('assessment-data/<int:pk>', login_required(views.ajax_assessment_data), name='ajax_assessment_data'),
        path('save-assessment-data/', login_required(views.ajax_save_assessment_data), name='ajax_save_assessment_data'),
        path('save-comment/', login_required(views.ajax_save_comment), name='ajax_save_comment'),
        path('delete-comment/', login_required(views.ajax_delete_comment), name='ajax_delete_comment'),
        path('choose-active-company/', login_required(views.ajax_choose_active_company), name='ajax_choose_active_company'),
    ])),

    #observer routes
    path('users/<int:student_id>/', include([
        path('roadmaps/<int:roadmap_id>/', login_required(views.roadmap), name='user_roadmap_observe'),
        path('competency/', include([
            path('<int:pk>/', login_required(views.CompetencyDetailView.as_view()), name='user_competency_observe'),
            # path('<int:pk>/edit/', login_required(views.CompetencyDetailView.as_view()), kwargs={'edit': True}, name='competency_admin_edit'),
            path('<int:competency_id>/comment/', login_required(views.CompetencyCommentsView.as_view()), name='competency_comments'),
            path('<int:competency_id>/comment/<int:comment_id>/', login_required(views.CompetencyCommentView.as_view()), name='competency_comment'),
        ])),
    ])),

    # staff routes
    path('staff/', include([
        path('companies/', include([
            path('', views.staff_companies, name='staff_companies'),
            path('add/', views.staff_companies_add_edit, name='staff_companies_add'),
            path('<int:pk>/edit/', views.staff_companies_add_edit, name='staff_companies_add_edit'),
            path('<int:pk>/edit/', views.coach_users_edit, name='coach_users_edit'),
        ])),
        path('roadmaps/', include([
            path('', views.staff_roadmaps, name='staff_roadmaps'),
            path('add/', views.staff_add_roadmap, name='staff_roadmaps_add'),
            path('add-template/<int:template_roadmap_id>', views.add_roadmap_template_staff, name='add_roadmap_template_staff'),
            path('copy/<int:pk>', views.copy_roadmap_staff, name='copy_roadmap_staff'),
            path('<int:pk>/', views.staff_roadmap, name='staff_roadmap'),
            path('<int:roadmap_id>/stats/', views.roadmap_stats, name='roadmap_stats'),
            path('<int:pk>/edit/', views.staff_edit_roadmap, name='staff_roadmap_edit'),
            path('<int:roadmap_id>/edit-roadmap-cohorts/', views.staff_edit_roadmap_cohorts, name='staff_edit_roadmap_cohorts'),
            path('<int:cohort_id>/assign-roadmap/<int:roadmap_id>', views.assign_roadmap_to_group, name='assign_roadmap_to_group'),
            path('<int:cohort_id>/unassign-roadmap/<int:roadmap_id>', views.unassign_roadmap_to_group, name='unassign_roadmap_to_group'),
            path('<int:roadmap_id>/pin-roadmap/', views.pin_roadmap, name='pin_roadmap'),
            path('<int:roadmap_id>/unpin-roadmap/', views.unpin_roadmap, name='unpin_roadmap'),
            path('<int:roadmap_id>/hide-roadmap-from-users/', views.hide_roadmap_from_users, name='hide_roadmap_from_users'),
            path('<int:roadmap_id>/unhide-roadmap-from-users/', views.unhide_roadmap_from_users, name='unhide_roadmap_from_users'),
            path('<int:roadmap_id>/assign-roadmap-to-all-users/', views.assign_roadmap_to_all_users, name='assign_roadmap_to_all_users'),
            path('<int:roadmap_id>/unassign-roadmap-to-all-users/', views.unassign_roadmap_to_all_users, name='unassign_roadmap_to_all_users'),
        ])),
        path('stage/copy/<int:pk>', views.copy_stage_staff, name='copy_stage_staff'),
        path('competencies/', include([
            path('copy/<int:pk>', views.copy_competency_staff, name='copy_competency_staff'),
            path('add/', login_required(views.CompetencyAddView.as_view()), name='staff_competency_add'),
            path('<int:pk>/', login_required(views.CompetencyDetailView.as_view()), kwargs={'staff': True}, name='staff_competency'),
            path('<int:pk>/edit/', login_required(views.CompetencyDetailView.as_view()), kwargs={'edit': True, 'staff': True}, name='staff_competency_edit'),
        ])),
        path('groups/', include([
            path('', views.staff_cohorts, name='staff_cohorts'),
            path('add/', views.staff_add_edit_cohorts, name='staff_cohorts_add'),
            path('<int:cohort_id>/', login_required(views.SCMList.as_view()), name='staff_cohort'),
            path('<int:cohort_id>/edit', views.staff_add_edit_cohorts, name='staff_cohort_edit'),
        ])),
        path('users/', include([
            path('', views.staff_users, name='staff_users'),
            path('add/', views.staff_users_add_edit, name='staff_users_add'),
            path('<int:pk>/', login_required(views.ProfileDetailView.as_view()), kwargs=dict(from_users=True), name='staff_user'),
            path('<int:pk>/edit/', views.staff_users_add_edit, name='staff_user_edit'),
            path('<int:pk>/send_welcome_email/', views.staff_users_send_welcome_email, name='staff_users_send_welcome_email'),
            path('<int:pk>/coach-edit/', views.coach_users_add_edit, name='coach_user_edit'),
            path('<int:student_id>/archive-roadmap/<int:roadmap_id>', views.archive_roadmap, name='archive_roadmap'),
            path('<int:student_id>/assign-roadmap/<int:roadmap_id>', views.assign_roadmap, name='assign_roadmap'),
            path('<int:student_id>/reassign-roadmap/<int:roadmap_id>', views.reassign_roadmap, name='reassign_roadmap'),
            path('<int:student_id>/remove-roadmap/<int:roadmap_id>', views.remove_roadmap, name='remove_roadmap'),
            path('<int:student_id>/staff-edit-user-roadmaps/', views.staff_edit_user_roadmaps, name='staff_edit_user_roadmaps'),
            path('<int:student_id>/add-edit-user-specific-objective/<int:stage_id>', views.add_user_specific_objective, name='add_user_specific_objective'),
            path('add-edit-user-specific-objective/<int:competency_id>', views.edit_user_specific_objective, name='edit_user_specific_objective'),
            path('<int:student_id>/hide-user-objective/<int:competency_id>', views.hide_user_objective, name='hide_user_objective'),
            path('<int:student_id>/unhide-user-objective/<int:competency_id>', views.unhide_user_objective, name='unhide_user_objective'),
            path('<int:student_id>/hide-all-stage-objectives/<int:stage_id>', views.hide_all_stage_objectives, name='hide_all_stage_objectives'),
            path('<int:student_id>/show-all-stage-objectives/<int:stage_id>', views.show_all_stage_objectives, name='show_all_stage_objectives'),
            path('deactivate-account/<int:user_id>', views.deactivate_account, name='deactivate_account'),
            path('activate-account/<int:user_id>', views.activate_account, name='activate_account'),
        ])),
    ])),
]
