<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_RA</name>
   <tag></tag>
   <elementGuidId>93be1d21-bec4-4326-8618-7848b61147ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fixed-actual-header > div.common-desktop-header > div.top-menu-container > div.container > div.row > div.right-menu.d-flex.align-items-center.justify-content-end.pr-0.col > div.menu-item.dropdown > div.menu-item-container > div.common-user-avatar > div.initials.md.mx-auto.small > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div[2]/div/div[2]/div/div/div/div/div[2]/div[3]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;home-app&quot;]/div[@class=&quot;page-container light&quot;]/div[@class=&quot;dashboard-dashboard-page&quot;]/div[@class=&quot;dashboard-admin-page&quot;]/div[@class=&quot;common-desktop-header-container d-none d-lg-block&quot;]/div[@class=&quot;fixed-actual-header&quot;]/div[@class=&quot;common-desktop-header&quot;]/div[@class=&quot;top-menu-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;right-menu d-flex align-items-center justify-content-end pr-0 col&quot;]/div[@class=&quot;menu-item dropdown&quot;]/div[@class=&quot;menu-item-container&quot;]/div[@class=&quot;common-user-avatar&quot;]/div[@class=&quot;initials md mx-auto small&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div/div[2]/div/div/div/div/div[2]/div[3]/div/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[2]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coaching'])[2]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roadmap Stats'])[2]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[3]/div/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
